### ISSUE TITLE
ImportError: No module named importlib

### ISSUE THREAD

**Issue by vishnusajev** [hovel/imagestore#68]
> File "/home/vishnu/sarath/ev/local/lib/python2.7/site-packages/imagestore/models/bases/image.py", line 21, in <module>
>     from imagestore.utils import FilePathGenerator
>   File "/home/vishnu/sarath/ev/local/lib/python2.7/site-packages/imagestore/utils.py", line 8, in <module>
>     from django.utils.importlib import import_module

From django 1.9 onwards `django.utils.importlib` has been removed now its been changed to `from importlib import import_module`. Please fix this, and by the way awesome package.

**Comment by lampslave** [comment]
Use code from this git repo, import was fixed long ago, see ca73f45cac8bcb39a3c779197b3bc2fb2ef50fff

**Comment by krisavi** [comment]
Ok, but how can I get it to work with imagestore from pip. When will the changes pushed to there?

**Comment by lampslave** [comment]
When imagestore will support django 1.8 and 1.11.

**Comment by krisavi** [comment]
It seems it supports 1.8 but not 1.9, tried also from the git clone and still not possible to migrate on 1.9, 1.10 nor 1.11.

**Comment by lampslave** [comment]
Release 3.0.0 on pypi. Feel free to report new bugs...
